### ISSUE TITLE
it's too simple

### ISSUE THREAD

**Issue by luckypoem** [kaoskorobase/declaredvolatile#2]
hi.

i setup a blog : http://dvo.bright.biz.st/blog/ as per ur repo.but there is even no index.html under blog/ subdir.so can u update ur code to generate the index.html file under blog/ subdir?

**Comment by kaoskorobase** [comment]
AFAICS the toplevel `index.html` lists the blog posts, you just have to adjust the path to generate it under `blog/index.html`.

**Comment by luckypoem** [comment]
hi.

even your site: http://declaredvolatile.org/blog/,there is also no index.html file under the blog subdir.
